-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, "%Y") AS YEAR, DATE_FORMAT(SALES_DATE, "%m") AS MONTH, GENDER, COUNT(DISTINCT(USER_INFO.USER_ID)) AS USERS
FROM USER_INFO INNER JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER ASC;
