-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, "%Y") AS YEAR, DATE_FORMAT(SALES_DATE, "%m") AS MONTH, GENDER, COUNT(DISTINCT(USER_INFO.USER_ID)) AS USERS
FROM USER_INFO INNER JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER ASC;
# SELECT 
# DATE_format(SALES_DATE,"%Y") AS YEAR,
# DATE_format(SALES_DATE,"%m") AS MONTH,
# GENDER, count(distinct sale.USER_ID) AS USERS
# from ONLINE_SALE AS sale left join USER_INFO AS info
# on sale.USER_ID = info.USER_ID
# group by YEAR, MONTH, GENDER
# having GENDER is not null
# order by YEAR, MONTH, GENDER;