-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR FROM FIRST_HALF INNER JOIN (SELECT * FROM ICECREAM_INFO HAVING INGREDIENT_TYPE = 'fruit_based')
X ON FIRST_HALF.FLAVOR = X.FLAVOR
WHERE TOTAL_ORDER > 3000
ORDER BY FLAVOR;
