-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM (
    SELECT MEMBER_ID, COUNT(MEMBER_ID), DENSE_RANK() OVER(ORDER BY COUNT(MEMBER_ID) DESC) AS RAN
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
) A NATURAL JOIN MEMBER_PROFILE JOIN REST_REVIEW USING (MEMBER_ID)
WHERE A.RAN = 1
ORDER BY REVIEW_DATE, REVIEW_TEXT;
